### ISSUE TITLE
部署摘要: agent异常退出:agent run error(unexpected):stop supervisor: e8771b72-8e28-49d8-ab25-3b9ff4cbf37b

### ISSUE THREAD

**Issue by danny-zhu** [DTStack/chengying#40]
项目打包部署过程中出现如下的错误提示：
部署摘要: agent异常退出:agent run error(unexpected):stop supervisor: e8771b72-8e28-49d8-ab25-3b9ff4cbf37b

schema.yml内容如下：
```
parent_product_name: top-lab
product_name: top-lab
product_name_display: top-lab
product_version: 1.0.0

service:

  TopLab:
    service_display: top-lab
    version: 1.0.1
    group: top-ai
    config:
      service_port: 8097
      self_ip: ${@TopLab}
      top_lab_ip_port: ${self_ip}:${service_port} #self service's node ip
      # java_opts: "-Xms256m -Xmx1024m -Dundertow.port=${service_port} -Dundertow.host=0.0.0.0"

    instance:
      cmd: ./start.sh start
      update_recreate: true
#      environment:
#        JAVA_OPTS: ${java_opts}
#      config_paths:
#      - config/jboot.properties
#      - config/jboot-dev.properties
      healthcheck:
        shell: curl http://${top_lab_ip_port}/healthcheck
        #period: 30s #default 60s
        start_period: 30s #default 10s
        timeout: 10s #default 10s
        retries: 3 #default 1
      max_replica: 1
      start_after_install: false
      #post_deploy: chown 0644 dtlog && zkcreate node xxx --ip ${@es}
      #post_undeploy: rm -rf /var/data/dtlog
      logs:
      - logs/output.log
```

承影matrix日志如下：
```
MATRIX-DEBUG:2023/09/13 14:07:22 cluster.go:3875: GetClusterProductList: /api/v2/cluster/products
MATRIX-DEBUG:2023/09/13 14:07:24 product_line.go:308: [ProductLine->ProductListOfProductLine] ProductListOfProductLine from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1578: [ProductName] ProductName from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product_line.go:308: [ProductLine->ProductListOfProductLine] ProductListOfProductLine from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:26 product.go:9035: [Product->CheckDeployCondition] CheckDeployCondition from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:26 cluster.go:520: RoleInfo: /api/v2/cluster/hosts/role_info?cluster_id=2
MATRIX-ERROR:2023/09/13 14:07:26 product.go:2204: [Product->ServiceGroup] handleUncheckedServicesCore warn: /var/jenkins_home/jobs/em-rel/jobs/chengying_release/workspace/chengying/chengying-server/matrix/api/impl/product.go:5156: unchecked service `` not exist
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:5218: deploy product_name:top-lab, product_version: 1.0.0, userId: 1, clusterId: 2
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4631: cluster 2 installing new instance and rolling update ...
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4492: cluster 2 rollingUpdateCore TopLab ...
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4331: cluster 2 found TopLab old instance ip: [192.168.14.6]
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4346: found TopLab new instance ip: []
MATRIX-ERROR:2023/09/13 14:07:27 product.go:5228: delete notify event error: sql: no rows in result set
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:164: [AgentClient] AgentStop with params:e8771b72-8e28-49d8-ab25-3b9ff4cbf37b
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:77: [AgentRestCore]LoopAgentRestCore: 1, request uri: /api/v1/agent/e8771b72-8e28-49d8-ab25-3b9ff4cbf37b/stopSync
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:81: [AgentRestCore]LoopAgentRestCore: 1, response body: &{ 0 <nil>}
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:154: [AgentClient] AgentStart with params:&{e8771b72-8e28-49d8-ab25-3b9ff4cbf37b 0 0 0 map[]}
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:77: [AgentRestCore]LoopAgentRestCore: 1, request uri: /api/v1/agent/e8771b72-8e28-49d8-ab25-3b9ff4cbf37b/startSyncWithParam
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:81: [AgentRestCore]LoopAgentRestCore: 1, response body: &{ 0 <nil>}
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:3622: waiting instance(15) GetStatusChan...
MATRIX-DEBUG:2023/09/13 14:07:35 instance.go:528: ExecShellList GetBySeq error: 0
MATRIX-ERROR:2023/09/13 14:07:35 product.go:3643: agent异常退出:agent run error(unexpected):stop supervisor: e8771b72-8e28-49d8-ab25-3b9ff4cbf37b
MATRIX-DEBUG:2023/09/13 14:07:35 product.go:3624: end instance(15) GetStatusChan
MATRIX-DEBUG:2023/09/13 14:07:35 instancer.go:864: [Instancer] Clear
MATRIX-DEBUG:2023/09/13 14:07:35 product.go:4498: rollingUpdateCore TopLab finish(cluster 2 some instance of TopLab update fail)
MATRIX-ERROR:2023/09/13 14:07:35 product.go:4634: 462d4cd3-3814-4fc1-b47c-2e699d02b45e update error: cluster 2 some instance of TopLab update fail
MATRIX-ERROR:2023/09/13 14:07:35 product.go:4554: sql: no rows in result set
MATRIX-ERROR:2023/09/13 14:07:35 product.go:4610: sql: no rows in result set
MATRIX-DEBUG:2023/09/13 14:07:22 cluster.go:3875: GetClusterProductList: /api/v2/cluster/products
MATRIX-DEBUG:2023/09/13 14:07:24 product_line.go:308: [ProductLine->ProductListOfProductLine] ProductListOfProductLine from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1578: [ProductName] ProductName from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product_line.go:308: [ProductLine->ProductListOfProductLine] ProductListOfProductLine from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:2003: Service: /api/v2/product/top-lab/version/1.0.0/service
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:24 product.go:1741: [Product->ProductUncheckedServices] get unchecked services from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:26 product.go:9035: [Product->CheckDeployCondition] CheckDeployCondition from EasyMatrix API
MATRIX-DEBUG:2023/09/13 14:07:26 cluster.go:520: RoleInfo: /api/v2/cluster/hosts/role_info?cluster_id=2
MATRIX-ERROR:2023/09/13 14:07:26 product.go:2204: [Product->ServiceGroup] handleUncheckedServicesCore warn: /var/jenkins_home/jobs/em-rel/jobs/chengying_release/workspace/chengying/chengying-server/matrix/api/impl/product.go:5156: unchecked service `` not exist
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:5218: deploy product_name:top-lab, product_version: 1.0.0, userId: 1, clusterId: 2
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4631: cluster 2 installing new instance and rolling update ...
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4492: cluster 2 rollingUpdateCore TopLab ...
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4331: cluster 2 found TopLab old instance ip: [192.168.14.6]
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:4346: found TopLab new instance ip: []
MATRIX-ERROR:2023/09/13 14:07:27 product.go:5228: delete notify event error: sql: no rows in result set
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:164: [AgentClient] AgentStop with params:e8771b72-8e28-49d8-ab25-3b9ff4cbf37b
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:77: [AgentRestCore]LoopAgentRestCore: 1, request uri: /api/v1/agent/e8771b72-8e28-49d8-ab25-3b9ff4cbf37b/stopSync
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:81: [AgentRestCore]LoopAgentRestCore: 1, response body: &{ 0 <nil>}
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:154: [AgentClient] AgentStart with params:&{e8771b72-8e28-49d8-ab25-3b9ff4cbf37b 0 0 0 map[]}
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:77: [AgentRestCore]LoopAgentRestCore: 1, request uri: /api/v1/agent/e8771b72-8e28-49d8-ab25-3b9ff4cbf37b/startSyncWithParam
MATRIX-DEBUG:2023/09/13 14:07:27 agent-client.go:81: [AgentRestCore]LoopAgentRestCore: 1, response body: &{ 0 <nil>}
MATRIX-DEBUG:2023/09/13 14:07:27 product.go:3622: waiting instance(15) GetStatusChan...
MATRIX-DEBUG:2023/09/13 14:07:35 instance.go:528: ExecShellList GetBySeq error: 0
MATRIX-ERROR:2023/09/13 14:07:35 product.go:3643: agent异常退出:agent run error(unexpected):stop supervisor: e8771b72-8e28-49d8-ab25-3b9ff4cbf37b
MATRIX-DEBUG:2023/09/13 14:07:35 product.go:3624: end instance(15) GetStatusChan
MATRIX-DEBUG:2023/09/13 14:07:35 instancer.go:864: [Instancer] Clear
MATRIX-DEBUG:2023/09/13 14:07:35 product.go:4498: rollingUpdateCore TopLab finish(cluster 2 some instance of TopLab update fail)
MATRIX-ERROR:2023/09/13 14:07:35 product.go:4634: 462d4cd3-3814-4fc1-b47c-2e699d02b45e update error: cluster 2 soMATRIX-DEBUG:2023/09/13 14:07:52 cluster_status_monitor.go:48: StartClusterStatusM ...
```
